import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter } from 'react-router-dom';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { AuthProvider } from './auth';
import { Login } from './pages/Login';
import { App } from './App';
import './style.css';
const client = new QueryClient({ defaultOptions: { queries: { retry: 1, staleTime: 10000 } } });
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><QueryClientProvider client={client}><BrowserRouter><AuthProvider login={<Login/>}><App/></AuthProvider></BrowserRouter></QueryClientProvider></React.StrictMode>);
